"""Add completions column to tasks

Revision ID: fdc99d5ee5be
Revises: 78ba2ea26480
Create Date: 2024-12-21 23:13:22.642655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc99d5ee5be'
down_revision: Union[str, None] = '78ba2ea26480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
